variables:
  DOCKER: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  GIT_DEPTH: 1
  CONTAINER_NAME_DEV: maukirim_dev
  CONTAINER_NAME_PROD: maukirim_prod
  DOCKER_TLS_CERTDIR: "/certs"


stages:
  - build
  - deploy
  - build_prod
  - deploy_prod

build:
  image: docker:latest
  services:
    - name: docker:dind
      alias: dockerhost
      entrypoint: [ "dockerd-entrypoint.sh", "--tls=false" ]
  stage: build
  variables:
    DOCKER_HOST: tcp://dockerhost:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - if [ ${DEV_ENV} ]; then cp ${DEV_ENV} .env; fi;
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t ${DOCKER}
    - docker push ${DOCKER}
    - docker rmi ${DOCKER}
  interruptible: true
  only:
    - develop

build_prod:
  image: docker:latest
  services:
    - name: docker:dind
      alias: dockerhost
      entrypoint: [ "dockerd-entrypoint.sh", "--tls=false" ]
  stage: build_prod
  variables:
    DOCKER_HOST: tcp://dockerhost:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - if [ ${PROD_ENV} ]; then cp ${PROD_ENV} .env; fi;
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t ${DOCKER}
    - docker push ${DOCKER}
    - docker rmi ${DOCKER}
  interruptible: true
  only:
    - tags
  except:
    - branches
deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$PRIMARY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ${SAFE_USER}@${SERVER_CONTABO} "docker login ${REGISTRY} -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN} && docker pull ${DOCKER} && docker stop ${CONTAINER_NAME_DEV} && docker rm ${CONTAINER_NAME_DEV} && docker run -d --name=${CONTAINER_NAME_DEV} -p 0.0.0.0:3001:3000 ${DOCKER}  && docker system prune -f && docker logout registry.gitlab.com;"
  interruptible: true
  only:
    - develop

deploy_prod:
  stage: deploy_prod
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$PRIMARY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ${SAFE_USER}@${SERVER_CONTABO_PROD} "docker login ${REGISTRY} -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN} && docker pull ${DOCKER} && docker stop ${CONTAINER_NAME_PROD} && docker rm ${CONTAINER_NAME_PROD} && docker run -d --name=${CONTAINER_NAME_PROD} -p 0.0.0.0:3001:3000 ${DOCKER}  && docker system prune -f && docker logout registry.gitlab.com;"
  interruptible: true
  only:
    - tags
  except:
    - branches